### ISSUE TITLE
Increase size?

### ISSUE THREAD

**Issue by NithanK** [BiAtoms/LinearProgressView#1]
Hey I was just wondering how to increase the size of the progress bar?

**Comment by nicolasspragg** [comment]
I'm trying to figure this out too

**Comment by OrkhanAlikhanov** [comment]
I didn't get what you mean. I set its size by constraints, you can see the example app

**Comment by OrkhanAlikhanov** [comment]
I didn't heard anything of you, so I am closing the issue. If the problem hasn't solved, feel free to reopen.
